Repository Matching42/Matching42-front, pull requests merged in 2021-06, with the labels that each got.

#48 배포 브랜치 병합 및 URL 라우팅 문제 해결
  .github/workflows/deploy.yml
  public/404.html
  public/index.html
  src/components/TeamMemberView/TeamMemberView.js
  src/components/TeamMemberView/TeamMemberView.styles.js
  src/components/TeamProfileView/TeamProfileView.js
  src/components/TeamProfileView/TeamProfileView.styles.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/pages/DetailPage.js
Labels: environment

#54 `Dialog(Modal)` 기능 구현
  .github/workflows/deploy.yml
  package.json
  public/404.html
  public/index.html
  src/assets/icons/icon-close.svg
  src/components/Dialog/Dialog.js
  src/components/Dialog/Dialog.styles.js
  src/components/DialogCloseButton/DialogCloseButton.js
  src/components/DialogCloseButton/DialogCloseButton.styles.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/MatchingStateView/MatchingStateView.styles.js
  src/components/SurveyForm/SurveyForm.js
  src/components/SurveyForm/SurveyForm.styles.js
  src/hooks/useToggleDialog.js
  src/pages/MainPage.js
Labels: feature

#52 Detail Page > TeamProfile 컴포넌트 구현
  src/app.js
  src/assets/icons/edit_team_profile_icon.svg
  src/components/Dday/Dday.js
  src/components/Dday/Dday.styles.js
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamProfileView/TeamProfileView.js
  src/components/TeamProfileView/TeamProfileView.styles.js
  src/hooks/useTeamListData.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
Labels: feature

#58 팀 인원, 태그 일정 수 이상 시 CSS 변경
  src/assets/icons/TeamListItem_Lock.svg
  src/assets/icons/TeamMemberView_Crown.svg
  src/assets/icons/TeamMemberView_Empty.svg
  src/assets/icons/TeamMemberView_Lock.svg
  src/assets/icons/TeamMemberView_Unlock.svg
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamListItem/common/HashTag/HashTag.js
  src/components/TeamListItem/common/TeamImage/TeamImage.js
  src/components/TeamListItem/common/TeamImage/TeamImage.styles.js
  src/components/TeamMemberView/TeamMemberImage/TeamMemberImage.js
  src/components/TeamMemberView/TeamMemberImage/TeamMemberImageStyled.js
  src/components/TeamMemberView/TeamMemberView.js
  src/components/TeamMemberView/TeamMemberView.styles.js
  src/components/TeamProfileView/TeamProfileView.js
  src/hooks/useTeamListData.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
  yarn.lock
Labels: feature

#60 Team Workspace Link 컴포넌트 구현
  package.json
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
Labels: feature

#62 2차 리팩토링
  package.json
  src/app.js
  src/assets/icons/TeamListItem_Lock.svg
  src/assets/icons/TeamMemberView_Crown.svg
  src/assets/icons/TeamMemberView_Empty.svg
  src/assets/icons/edit_team_profile_icon.svg
  src/assets/icons/icon-close.svg
  src/assets/icons/icon-lock.svg
  src/assets/icons/icon-unlock.svg
  src/components/Dday/Dday.js
  src/components/Dday/Dday.styles.js
  src/components/Dialog/Dialog.js
  src/components/Dialog/Dialog.styles.js
  src/components/DialogCloseButton/DialogCloseButton.js
  src/components/DialogCloseButton/DialogCloseButton.styles.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/MatchingStateView/MatchingStateView.styles.js
  src/components/SurveyForm/SurveyForm.js
  src/components/SurveyForm/SurveyForm.styles.js
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamListItem/common/HashTag/HashTag.js
  src/components/TeamListItem/common/TeamImage/TeamImage.js
  src/components/TeamListItem/common/TeamImage/TeamImage.styles.js
  src/components/TeamMemberView/TeamMemberImage/TeamMemberImage.js
  src/components/TeamMemberView/TeamMemberImage/TeamMemberImageStyled.js
  src/components/TeamMemberView/TeamMemberView.js
  src/components/TeamMemberView/TeamMemberView.styles.js
  src/components/TeamProfileView/TeamProfileView.js
  src/components/TeamProfileView/TeamProfileView.styles.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/hooks/useTeamListData.js
  src/hooks/useToggleDialog.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
  yarn.lock
Labels: refactoring

#57 공통 > Dropdown 컴포넌트 구현
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.styles.js
  src/components/TeamListView/TeamListView.js
  src/pages/MainPage.js
Labels: feature

#64 2차 리팩토링 추가 반영
  src/assets/images/42_logo.svg
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.styles.js
  src/components/Header/Header.js
  src/components/Header/Header.styles.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/TeamListView/TeamListView.js
  src/hooks/useTeamListData.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
Labels: refactoring

#66 Dropdown 컴포넌트 개선 및 애니메이션 적용
  src/assets/icons/SVG.js
  src/assets/icons/icon-arrow.svg
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.styles.js
  yarn.lock
Labels: feature

#56 `SurveyForm` 컴포넌트 구현
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.styles.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/RadioButton/RadioButton.js
  src/components/RadioButton/RadioButton.styles.js
  src/components/SurveyForm/SurveyForm.js
  src/components/SurveyForm/SurveyForm.styles.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
  src/components/TextInput/TextInput.js
  src/components/TextInput/TextInput.styles.js
  src/components/ToggleButton/ToggleButton.styles.js
  src/pages/MainPage.js
Labels: feature

#71 팀 멤버 자물쇠 아이콘 클릭 동작 구현
  package.json
  src/assets/icons/icon-teamListItemLock.svg
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
  src/components/TeamMemberView/TeamMemberView.js
  src/components/ToggleButton/ToggleButton.js
  src/components/ToggleButton/ToggleButton.styles.js
  src/components/loaderSpinner/loaderSpinner.js
  src/pages/DetailPage.js
  yarn.lock
Labels: feature

#76 커스텀 알림창 구현 후, 스터디 종료 시 뜨도록 적용
  package.json
  src/assets/icons/DropdownIcon.js
  src/assets/icons/icon-arrow.svg
  src/assets/icons/icon-teamListItemLock.svg
  src/components/Dialog/Dialog.js
  src/components/Dialog/Dialog.styles.js
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.styles.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/RadioButton/RadioButton.js
  src/components/RadioButton/RadioButton.styles.js
  src/components/SurveyForm/SurveyForm.js
  src/components/SurveyForm/SurveyForm.styles.js
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
  src/components/TeamMemberView/TeamMemberView.js
  src/components/TeamProfileView/TeamProfileView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/components/TextInput/TextInput.js
  src/components/TextInput/TextInput.styles.js
  src/components/ToggleButton/ToggleButton.js
  src/components/ToggleButton/ToggleButton.styles.js
  src/components/loaderSpinner/loaderSpinner.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
  yarn.lock
Labels: feature

#77 feature: 로그아웃 UI 구현
  src/components/Dialog/Dialog.js
  src/components/Dialog/Dialog.styles.js
  src/components/Header/Header.js
  src/components/Header/Header.styles.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/pages/DetailPage.js
Labels: feature

#79 3차 코드 리팩토링
  src/components/Header/Header.js
  src/components/Header/Header.styles.js
  src/components/TeamListView/TeamListView.styles.js
  src/components/TeamProfileView/TeamProfileView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
Labels: refactoring

#81 로그인 연동 및 리다이렉션 적용
  package.json
  src/api/index.js
  src/app.js
  src/components/Header/Header.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/ProfileView/ProfileView.js
  src/components/TeamMemberView/TeamMemberView.js
  src/hooks/useUserData.js
  src/pages/DetailPage.js
  src/pages/LoginPage.js
  src/pages/MainPage.js
  src/store/auth.js
  yarn.lock
Labels: feature

#87 블랙홀 현재 날짜 기준으로 계산해서 표시
  src/components/Header/Header.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/MatchingStateView/MatchingStateView.styles.js
  src/components/ProfileView/ProfileView.js
  src/components/SurveyForm/SurveyForm.js
  src/pages/MainPage.js
Labels: hotfix

#84 매칭 버튼 > 설문 폼 작성 완료 시 POST
  src/components/MatchingStateView/MatchingStateView.js
  src/components/MatchingStateView/MatchingStateView.styles.js
  src/components/SurveyForm/SurveyForm.js
  src/pages/MainPage.js
Labels: feature

#86 MainPage 팀 데이터 연동, 로딩 전 유저 이미지 처리
  package.json
  src/app.js
  src/assets/icons/icon-nonPeople.svg
  src/components/Dday/Dday.js
  src/components/Header/Header.js
  src/components/MyTeamListView/MyTeamListView.js
  src/components/MyTeamListView/MyTeamListView.styles.js
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamListItem/common/TeamImage/TeamImage.js
  src/components/TeamListItem/common/TeamImage/TeamImage.styles.js
  src/components/TeamMemberView/TeamMemberImage/TeamMemberImage.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/hooks/useTeamListData.js
  src/hooks/useUserData.js
  src/pages/MainPage.js
  yarn.lock
Labels: feature

#89 4차 코드 리팩토링
  package.json
  src/api/index.js
  src/app.js
  src/assets/icons/icon-nonPeople.svg
  src/components/Dday/Dday.js
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.styles.js
  src/components/Header/Header.js
  src/components/Header/Header.styles.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/MatchingStateView/MatchingStateView.styles.js
  src/components/MyTeamListView/MyTeamListView.js
  src/components/MyTeamListView/MyTeamListView.styles.js
  src/components/ProfileView/ProfileView.js
  src/components/SurveyForm/SurveyForm.js
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamListItem/common/HashTag/HashTag.js
  src/components/TeamListItem/common/HashTag/HashTag.styles.js
  src/components/TeamListItem/common/TeamImage/TeamImage.js
  src/components/TeamListItem/common/TeamImage/TeamImage.styles.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
  src/components/TeamMemberView/TeamMemberImage/TeamMemberImage.js
  src/components/TeamMemberView/TeamMemberImage/TeamMemberImageStyled.js
  src/components/TeamMemberView/TeamMemberView.js
  src/components/TeamMemberView/TeamMemberView.styles.js
  src/components/TeamProfileView/TeamProfileView.styles.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/components/TextInput/TextInput.js
  src/components/TextInput/TextInput.styles.js
  src/components/ToggleButton/ToggleButton.js
  src/components/loaderSpinner/loaderSpinner.js
  src/hooks/useTeamListData.js
  src/hooks/useUserData.js
  src/index.js
  src/pages/DetailPage.js
  src/pages/LoginPage.js
  src/pages/MainPage.js
  src/store/auth.js
  yarn.lock
Labels: refactoring

#95 `Main Page` 팀 리스트 클릭 시 넘겨받은 `id` 로 팀 정보 GET
  README.md
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.styles.js
  src/components/Header/Header.js
  src/components/Header/Header.styles.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/ProfileView/ProfileView.js
  src/components/SurveyForm/SurveyForm.js
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamListItem/common/HashTag/HashTag.js
  src/components/TeamListItem/common/HashTag/HashTag.styles.js
  src/components/TeamListItem/common/TeamImage/TeamImage.js
  src/components/TeamListItem/common/TeamImage/TeamImage.styles.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
  src/components/TeamMemberView/TeamMemberImage/TeamMemberImage.js
  src/components/TeamMemberView/TeamMemberImage/TeamMemberImageStyled.js
  src/components/TeamMemberView/TeamMemberView.styles.js
  src/components/TeamProfileView/TeamProfileView.js
  src/components/TeamProfileView/TeamProfileView.styles.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/components/TextInput/TextInput.js
  src/components/TextInput/TextInput.styles.js
  src/components/ToggleButton/ToggleButton.js
  src/components/loaderSpinner/loaderSpinner.js
  src/hooks/useStateData.js
  src/hooks/useTeamListData.js
  src/hooks/useUserData.js
  src/index.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
Labels: feature

#94 매칭 대기 인원수 GET 데이터 반영
  src/components/Header/Header.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/ProfileView/ProfileView.js
  src/hooks/useStateData.js
  src/pages/MainPage.js
Labels: feature

#97 `Team Workspace Link` 데이터 연동, 스터디 종료 버튼 클릭 시 팀 삭제 반영
  src/app.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
Labels: feature

#100 추가 디자인 사항 반영
  src/components/Header/Header.js
  src/components/LoaderSpinner/LoaderSpinner.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/MatchingStateView/MatchingStateView.styles.js
  src/components/MyTeamListView/MyTeamListView.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamProfileView/TeamProfileView.js
  src/components/TeamProfileView/TeamProfileView.styles.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
Labels: feature
