Repository Matching42/Matching42-front, pull requests merged in 2021-05, with the labels that each got.

#7 프로젝트 Git 세팅
  .github/.gitmessage
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue-template.md
Labels: environment

#8 프로젝트 Git setting
  .eslintrc.js
  .github/.gitmessage
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue-template.md
  .gitignore
  .prettierrc
  README.md
  package.json
  public/index.html
  src/api/index.js
  src/app.js
  src/components/Header/Header.js
  src/components/Header/Header.styles.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/MatchingStateView/MatchingStateView.styles.js
  src/components/MyTeamListView/MyTeamListView.js
  src/components/MyTeamListView/MyTeamListView.styles.js
  src/components/ProfileView/ProfileView.js
  src/components/ProfileView/ProfileView.styles.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
  src/hooks/useUserData.js
  src/index.js
  src/pages/MainPage.js
  yarn.lock
Labels: environment

#12 ProfileView 컴포넌트 구현
  src/components/ProfileView/ProfileView.js
  src/components/ProfileView/ProfileView.styles.js
Labels: feature

#13 TeamList, MyTeamList
  .gitmessage.txt
  package-lock.json
  src/components/MyTeamListView/MyTeamListView.js
  src/components/MyTeamListView/MyTeamListView.styles.js
  src/components/TeamListItemView/HashTag.styles.js
  src/components/TeamListItemView/HashTags.js
  src/components/TeamListItemView/TeamImg.js
  src/components/TeamListItemView/TeamImg.styles.js
  src/components/TeamListItemView/TeamListItemView.js
  src/components/TeamListItemView/TeamListItemView.styles.js
  src/components/TeamListView/Dropdown.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
  src/components/TeamListView/WaitToggleButton.js
  src/components/TeamListView/WaitToggleButton.styles.js
  src/hooks/useUserData.js
  src/pages/MainPage.js
Labels: feature

#21 TeamListView Infinite Scroll 구현
  src/components/TeamListItemView/TeamImg.js
  src/components/TeamListItemView/TeamListItemView.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
  src/components/TeamListView/WaitToggleButton.styles.js
Labels: feature

#23 TeamListView > Infinite Scroll 스크롤 바 CSS 수정
  src/app.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
Labels: feature

#30 Main Page - ProfileView 컴포넌트 구현
  src/components/ProfileView/ProfileView.js
  src/components/ProfileView/ProfileView.styles.js
Labels: feature

#19 Main Page - MatchingStateView 컴포넌트 구현
  src/components/MatchingStateView/MatchingStateView.js
  src/components/MatchingStateView/MatchingStateView.styles.js
Labels: refactoring

#32 1차 코드 리팩토링
  .eslintrc.js
  package-lock.json
  src/api/index.js
  src/app.js
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.styles.js
  src/components/Header/Header.js
  src/components/LoginSectionView/LoginSectionView.js
  src/components/LoginSectionView/LoginSectionView.styles.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/MatchingStateView/MatchingStateView.styles.js
  src/components/MyTeamListView/MyTeamListView.js
  src/components/MyTeamListView/MyTeamListView.styles.js
  src/components/ProfileView/ProfileView.js
  src/components/ProfileView/ProfileView.styles.js
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamListItem/TeamListItem.styles.js
  src/components/TeamListItem/common/HashTag/HashTag.js
  src/components/TeamListItem/common/HashTag/HashTag.styles.js
  src/components/TeamListItem/common/TeamImage/TeamImage.js
  src/components/TeamListItem/common/TeamImage/TeamImage.styles.js
  src/components/TeamListItemView/HashTags.js
  src/components/TeamListItemView/TeamImg.js
  src/components/TeamListItemView/TeamImg.styles.js
  src/components/TeamListItemView/TeamListItemView.js
  src/components/TeamListItemView/TeamListItemView.styles.js
  src/components/TeamListView/Dropdown.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
  src/components/TeamListView/WaitToggleButton.js
  src/components/TeamListView/WaitToggleButton.styles.js
  src/components/ToggleButton/ToggleButton.js
  src/components/ToggleButton/ToggleButton.styles.js
  src/hooks/useTeamListData.js
  src/pages/DetailPage.js
  src/pages/LoginPage.js
  src/pages/MainPage.js
Labels: refactoring

#42 상세 페이지 구조 설계 및 구현
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  package.json
  src/app.js
  src/components/TeamMemberView/TeamMemberView.js
  src/components/TeamMemberView/TeamMemberView.styles.js
  src/components/TeamProfileView/TeamProfileView.js
  src/components/TeamProfileView/TeamProfileView.styles.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/pages/DetailPage.js
  yarn.lock
Labels: feature
