Repository Matching42/Matching42-front, pull requests merged in 2021-07, with the labels that each got.

#98 로그아웃 폼 외부 클릭하거나 화면 이동 시 자동으로 닫히도록 수정 && 자물쇠 아이콘 따른 teamState FETCH
  src/assets/icons/icon-nonPeople.svg
  src/components/Header/Header.js
  src/components/Header/Header.styles.js
  src/components/Header/Logout.js
  src/components/Header/Logout.styles.js
  src/components/TeamMemberView/TeamMemberView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/hooks/patchTeamData.js
  src/hooks/useTeamListData.js
  src/hooks/useUserData.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
Labels: feature

#103 Detail Page > TeamProfileView EditButton 클릭 시 모달창 띄우기
  src/assets/icons/icon-delete.svg
  src/components/EditForm/EditForm.js
  src/components/EditForm/EditForm.styles.js
  src/components/TeamProfileView/TeamProfileView.js
  src/components/TeamProfileView/TeamProfileView.styles.js
  src/pages/DetailPage.js
Labels: feature

#102 5차 코드 리팩토링
  src/assets/icons/PlusIcon.js
  src/components/AddTag/AddTag.js
  src/components/AddTag/AddTag.styles.js
  src/components/EditForm/EditForm.js
  src/components/EditForm/EditForm.styles.js
  src/components/Header/Logout.js
  src/components/MyTeamListView/MyTeamListView.js
  src/components/MyTeamListView/MyTeamListView.styles.js
  src/components/TeamListView/TeamListView.js
  src/components/TeamListView/TeamListView.styles.js
  src/components/TeamMemberView/TeamMemberView.js
  src/hooks/useTeamListData.js
  src/hooks/useUserData.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
Labels: refactoring

#110 로그아웃 기능 적용
  src/app.js
  src/components/Header/Header.js
  src/components/Header/Logout.js
Labels: feature

#107 팀 리더가 아닌 경우 스터디 종료 버튼 비활성화
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/pages/DetailPage.js
Labels: feature

#111 매칭 신청 시 존재하지 않는 깃허브 아이디 에러 표시
  src/components/MatchingStateView/MatchingStateView.js
  src/components/SurveyForm/SurveyForm.js
  src/components/TextInput/TextInput.js
  src/pages/MainPage.js
Labels: hotfix

#112 해상도 높을 때 CSS 수정, totalSize, tags API 연동
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamListItem/common/HashTag/HashTag.js
  src/components/TeamListItem/common/TeamImage/TeamImage.styles.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/components/ToggleButton/ToggleButton.styles.js
  src/hooks/useUserData.js
  src/pages/MainPage.js
Labels: feature, hotfix

#118 TeamListView 서브젝트 드롭다운 외부 클릭 시 드롭다운 닫기
  src/components/Dropdown/Dropdown.js
Labels: feature

#119 매칭 신청 폼 라디오 버튼 Label 클릭 시에도 체크되게 수정
  src/components/RadioButton/RadioButton.js
  src/components/RadioButton/RadioButton.styles.js
Labels: feature

#122 매칭 신청 Bad Request일 때 사용자에게 오류 표시
  src/components/MatchingStateView/MatchingStateView.js
  src/components/SurveyForm/SurveyForm.js
  src/components/TextInput/TextInput.js
  src/pages/MainPage.js
Labels: feature

#124 매칭 신청에서 작성완료 버튼 눌렀을 때 모달이 닫히지 않는 문제 해결
  src/components/MatchingStateView/MatchingStateView.js
Labels: hotfix

#120 TeamWorkspace 스크롤이 잘려서 보이는 문제
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
Labels: hotfix

#121 팀 태그 등록 시 잘못된 태그 등록 막기
  src/components/AddTag/AddTag.js
  src/components/AddTag/AddTag.styles.js
  src/components/EditForm/EditForm.js
  src/components/TeamProfileView/TeamProfileView.js
  src/components/TeamProfileView/TeamProfileView.styles.js
Labels: feature

#129 팀장이 아닐 때 자물쇠 처리, My Team 없을 때 로딩 처리
  src/components/MyTeamListView/MyTeamListView.js
  src/components/TeamMemberView/TeamMemberView.js
  src/components/TeamMemberView/TeamMemberView.styles.js
Labels: feature

#128 팀이 종료된 상태일 때, 스터디 종료 버튼 없애고 자물쇠 비활성화 적용
  src/components/TeamListItem/TeamListItem.js
  src/components/TeamListItem/TeamListItem.styles.js
  src/components/TeamMemberView/TeamMemberView.js
  src/components/TeamMemberView/TeamMemberView.styles.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
Labels: feature

#131 서브젝트 필터링 드롭다운 전체보기 기능 적용
  src/assets/icons/icon-cancel.svg
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.styles.js
Labels: feature
