Repository Matching42/Matching42-front, pull requests merged in 2021-09, with the labels that each got.

#167 스터디 참여 버튼 구현
  src/components/TeamMemberView/TeamMemberView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/pages/DetailPage.js
Labels: feature

#169 화면 세로 사이즈 작을 때 스터디 참여/종료 버튼 위치 수정
  src/components/TeamMemberView/TeamMemberImage/TeamMemberImage.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
Labels: hotfix

#176 팀 정보 수정 모달 기존 태그 반영, 서브젝트 필터링 css 수평, 드롭다운 전체 클릭
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.styles.js
  src/components/EditForm/EditForm.js
  src/components/MatchingStateView/MatchingStateView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.js
  src/components/TeamWorkspaceView/TeamWorkspaceView.styles.js
  src/pages/DetailPage.js
  src/pages/MainPage.js
Labels: hotfix, feature
